export {
  StatCardSkeleton,
  StatCardGridSkeleton,
  SubjectCardSkeleton,
  SubjectCardsGridSkeleton,
  CalendarSkeleton,
  ClassHistoryItemSkeleton,
  ClassHistorySkeleton,
  UpcomingSessionSkeleton,
  UpcomingSessionsListSkeleton,
  TabsSkeleton,
  TableRowSkeleton,
  TableSkeleton,
  StudentDashboardSkeleton,
  TutorDashboardSkeleton,
  AdminDashboardSkeleton,
} from './DashboardSkeleton';
